// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/services/repobuilder.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/redhatinsights/edge-api/pkg/models"
)

// MockRepoBuilderInterface is a mock of RepoBuilderInterface interface.
type MockRepoBuilderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepoBuilderInterfaceMockRecorder
}

// MockRepoBuilderInterfaceMockRecorder is the mock recorder for MockRepoBuilderInterface.
type MockRepoBuilderInterfaceMockRecorder struct {
	mock *MockRepoBuilderInterface
}

// NewMockRepoBuilderInterface creates a new mock instance.
func NewMockRepoBuilderInterface(ctrl *gomock.Controller) *MockRepoBuilderInterface {
	mock := &MockRepoBuilderInterface{ctrl: ctrl}
	mock.recorder = &MockRepoBuilderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoBuilderInterface) EXPECT() *MockRepoBuilderInterfaceMockRecorder {
	return m.recorder
}

// BuildUpdateRepo mocks base method.
func (m *MockRepoBuilderInterface) BuildUpdateRepo(id uint) (*models.UpdateTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildUpdateRepo", id)
	ret0, _ := ret[0].(*models.UpdateTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildUpdateRepo indicates an expected call of BuildUpdateRepo.
func (mr *MockRepoBuilderInterfaceMockRecorder) BuildUpdateRepo(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildUpdateRepo", reflect.TypeOf((*MockRepoBuilderInterface)(nil).BuildUpdateRepo), id)
}

// DownloadExtractVersionRepo mocks base method.
func (m *MockRepoBuilderInterface) DownloadExtractVersionRepo(c *models.Commit, dest string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadExtractVersionRepo", c, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadExtractVersionRepo indicates an expected call of DownloadExtractVersionRepo.
func (mr *MockRepoBuilderInterfaceMockRecorder) DownloadExtractVersionRepo(c, dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadExtractVersionRepo", reflect.TypeOf((*MockRepoBuilderInterface)(nil).DownloadExtractVersionRepo), c, dest)
}

// ImportRepo mocks base method.
func (m *MockRepoBuilderInterface) ImportRepo(r *models.Repo) (*models.Repo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportRepo", r)
	ret0, _ := ret[0].(*models.Repo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportRepo indicates an expected call of ImportRepo.
func (mr *MockRepoBuilderInterfaceMockRecorder) ImportRepo(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportRepo", reflect.TypeOf((*MockRepoBuilderInterface)(nil).ImportRepo), r)
}
