// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/services/thirdpartyrepo.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/redhatinsights/edge-api/pkg/models"
	reflect "reflect"
)

// MockThirdPartyRepoServiceInterface is a mock of ThirdPartyRepoServiceInterface interface
type MockThirdPartyRepoServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockThirdPartyRepoServiceInterfaceMockRecorder
}

// MockThirdPartyRepoServiceInterfaceMockRecorder is the mock recorder for MockThirdPartyRepoServiceInterface
type MockThirdPartyRepoServiceInterfaceMockRecorder struct {
	mock *MockThirdPartyRepoServiceInterface
}

// NewMockThirdPartyRepoServiceInterface creates a new mock instance
func NewMockThirdPartyRepoServiceInterface(ctrl *gomock.Controller) *MockThirdPartyRepoServiceInterface {
	mock := &MockThirdPartyRepoServiceInterface{ctrl: ctrl}
	mock.recorder = &MockThirdPartyRepoServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockThirdPartyRepoServiceInterface) EXPECT() *MockThirdPartyRepoServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateThirdPartyRepo mocks base method
func (m *MockThirdPartyRepoServiceInterface) CreateThirdPartyRepo(tprepo *models.ThirdPartyRepo, account string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThirdPartyRepo", tprepo, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateThirdPartyRepo indicates an expected call of CreateThirdPartyRepo
func (mr *MockThirdPartyRepoServiceInterfaceMockRecorder) CreateThirdPartyRepo(tprepo, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThirdPartyRepo", reflect.TypeOf((*MockThirdPartyRepoServiceInterface)(nil).CreateThirdPartyRepo), tprepo, account)
}

// GetThirdPartyRepoByID mocks base method
func (m *MockThirdPartyRepoServiceInterface) GetThirdPartyRepoByID(ID string) (*models.ThirdPartyRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThirdPartyRepoByID", ID)
	ret0, _ := ret[0].(*models.ThirdPartyRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThirdPartyRepoByID indicates an expected call of GetThirdPartyRepoByID
func (mr *MockThirdPartyRepoServiceInterfaceMockRecorder) GetThirdPartyRepoByID(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThirdPartyRepoByID", reflect.TypeOf((*MockThirdPartyRepoServiceInterface)(nil).GetThirdPartyRepoByID), ID)
}

// UpdateThirdPartyRepo mocks base method
func (m *MockThirdPartyRepoServiceInterface) UpdateThirdPartyRepo(tprepo *models.ThirdPartyRepo, account, ID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThirdPartyRepo", tprepo, account, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThirdPartyRepo indicates an expected call of UpdateThirdPartyRepo
func (mr *MockThirdPartyRepoServiceInterfaceMockRecorder) UpdateThirdPartyRepo(tprepo, account, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThirdPartyRepo", reflect.TypeOf((*MockThirdPartyRepoServiceInterface)(nil).UpdateThirdPartyRepo), tprepo, account, ID)
}

// DeleteThirdPartyRepoByID mocks base method
func (m *MockThirdPartyRepoServiceInterface) DeleteThirdPartyRepoByID(ID string) (*models.ThirdPartyRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteThirdPartyRepoByID", ID)
	ret0, _ := ret[0].(*models.ThirdPartyRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteThirdPartyRepoByID indicates an expected call of DeleteThirdPartyRepoByID
func (mr *MockThirdPartyRepoServiceInterfaceMockRecorder) DeleteThirdPartyRepoByID(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteThirdPartyRepoByID", reflect.TypeOf((*MockThirdPartyRepoServiceInterface)(nil).DeleteThirdPartyRepoByID), ID)
}
