---
#
# Merge queue rules https://docs.mergify.com/actions/queue/#queue-rules
queue_rules:
  #
  # Add this PR to the merge queue
  - name: edge-api
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
#
# Pull request rules https://docs.mergify.com/configuration/#pull-request-rules
# N.B. Evaluated in order defined
pull_request_rules:
  #
  # Dependabot PR merge rule
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "#approved-reviews-by>=1"
      - check-success=Lint
      - check-success=Travis CI - Pull Request
    actions:
      queue:
        name: edge-api
        method: merge
        rebase_fallback: none
  #
  # If PR check fails, request resolution (prevent stalling the merge queue)
  - name: Request PR check re-run
    conditions:
      - and:
          - base=main
          - "#changes-requested-reviews-by=0"
          - "#approved-reviews-by>=1"
          - label!=work in progress
          - label!=do not merge
          - or:
              - -check-success=ci.int.devshift.net PR build
              - -check-success=Lint
              - -check-success=Travis CI - Pull Request
    actions:
      comment:
        message: "This pull request needs all pr-checks to run successfully. Could you fix it @{{author}}? 🙏"
      label:
        add:
          - invalid
  #
  # Non-dependabot Merge PR rule
  - name: Automatic merge on approval
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - check-success=Lint
      - check-success=Travis CI - Pull Request
      - check-success=ci.int.devshift.net PR build
      - label!=work in progress
      - label!=do not merge
    actions:
      label:
        remove:
          - invalid
      queue:
        name: edge-api
        method: merge
        rebase_fallback: none
  #
  # Detect when PR conflicts and add label
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "This pull request is now in conflicts. Could you fix it @{{author}}? 🙏"
      label:
        add:
          - conflict
  #
  # Detect when PR conflict is cleared and remove label
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  #
  # Automatically close PR after 14 days
  - name: close stale pull request
    conditions:
      - base=main
      - -closed
      - updated-at<14 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it's a mistake.
  #
  # Detect when PR is awaiting review and add label
  - name: waiting for review
    conditions:
      - "#commented-reviews-by<1"
      - created-at<1 days ago
      - -draft
    actions:
      label:
        add:
          - waiting for review
  #
  # Detect when PR received review and remove label
  - name: remove waiting for review label if not needed
    conditions:
      - "#commented-reviews-by>=1"
      - -draft
    actions:
      label:
        remove:
          - waiting for review
  #
  # Detect when PR includes a bug fix and add label
  - name: add bug fix label
    conditions:
      - body~=(?m)^\[X\] Bug fix (non-breaking change which fixes an issue)
    actions:
      label:
        add:
          - bug fix
  #
  # Detect when PR includes new feature and add label
  - name: add new feature label
    conditions:
      - body~=(?m)^\[X\] New feature (non-breaking change which adds functionality)
    actions:
      label:
        add:
          - new feature
  #
  # Detect when PR includes documentation updates and add label
  - name: add documentation label
    conditions:
      - body~=(?m)^\[X\] Documentation update
    actions:
      label:
        add:
          - documentation
  #
  # Detect when PR includes tests update and add label
  - name: add test update label
    conditions:
      - body~=(?m)^\[X\] Tests update
    actions:
      label:
        add:
          - test update
  #
  # Detect when PR no longer includes bug fix and remove label
  - name: remove bug fix label
    conditions:
      - body~=(?m)^\[ \] Bug fix (non-breaking change which fixes an issue)
    actions:
      label:
        remove:
          - bug fix
  #
  # Detect when PR no longer includes new feature and remove label
  - name: remove new feature label
    conditions:
      - body~=(?m)^\[ \] New feature (non-breaking change which adds functionality)
    actions:
      label:
        remove:
          - new feature
  #
  # Detect when PR no longer includes documentation updates and remove label
  - name: remove documentation label
    conditions:
      - body~=(?m)^\[ \] Documentation update
    actions:
      label:
        remove:
          - documentation
  #
  # Detect when PR no longer includes tests update and remove label
  - name: remove test update label
    conditions:
      - body~=(?m)^\[ \] Tests update
    actions:
      label:
        remove:
          - test update
  #
  # Detect when PR is ready and add label
  - name: add ready label
    conditions:
      - body~=(?m)^\[X\] I have commented my code, particularly in hard-to-understand areas
      - body~=(?m)^\[X\] I have made corresponding changes to the documentation
      - body~=(?m)^\[X\] I have added tests that prove my fix is effective or that my feature works
      - body~=(?m)^\[X\] New and existing unit tests pass locally with my changes
      - body~=(?m)^\[X\] I run `go fmt ./...` to check that my code is properly formatted
      - body~=(?m)^\[X\] I run `go vet ./...` to check that my code is free of common Go style mistakes
    actions:
      label:
        add:
          - ready
