---
#
# Shared keys
shared:
  my_ci: &common-merge-criteria
    - "#approved-reviews-by>=2"
    - "#changes-requested-reviews-by=0"
    - "#review-threads-unresolved=0"
#
# Merge queue rules https://docs.mergify.com/actions/queue/#queue-rules
queue_rules:
  #
  # Add this PR to the merge queue
  - name: edge-api
    conditions:
      - base=main
      - and: *common-merge-criteria
#
# Pull request rules https://docs.mergify.com/configuration/#pull-request-rules
# N.B. Evaluated in order defined
pull_request_rules:
  #
  # Remove stale approvals or changes request
  - name: Remove outdated reviews
    conditions:
      - base=main
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
        message: New commit(s) added, removing existing approval(s)
        when: synchronize
  #
  # Require all conversations to be resolved
  - name: Check for unresolved conversations before merging
    conditions:
      - "#review-threads-unresolved>0"
    actions:
      comment:
        message: "This pull request needs all conversation threads to be resolved. Could you fix it @{{author}}? 🙏"
      label:
        add:
          - question
  #
  # If all conversations to be resolved, remove question label
  - name: Remove question label from resolved conversations
    conditions:
      - "#review-threads-unresolved=0"
    actions:
      label:
        remove:
          - question
  #
  # Dependabot PR merge rule
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - and: *common-merge-criteria
      - check-success=Lint
      # - check-success=Travis CI - Pull Request
    actions:
      queue:
        name: edge-api
        method: merge
        rebase_fallback: none
  #
  # If PR check fails, request resolution (prevent stalling the merge queue)
  - name: Request PR check re-run
    conditions:
      - and:
          - base=main
          - and: *common-merge-criteria
          - label!=work in progress
          - label!=do not merge
          - updated-at<1 days ago
          - or:
              - -check-success=ci.int.devshift.net PR build
              - -check-success=Lint
              # - -check-success=Travis CI - Pull Request
    actions:
      comment:
        message: "This pull request needs all pr-checks to run successfully. Could you fix it @{{author}}? 🙏"
      label:
        add:
          - invalid
  #
  # Non-dependabot Merge PR rule
  - name: Automatic merge on approval
    conditions:
      - base=main
      - and: *common-merge-criteria
      - check-success=Lint
      # - check-success=Travis CI - Pull Request
      - check-success=ci.int.devshift.net PR build
      - label!=work in progress
      - label!=do not merge
    actions:
      label:
        remove:
          - invalid
      queue:
        name: edge-api
        method: merge
        rebase_fallback: none
  #
  # Detect when PR conflicts and add label
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "This pull request is now in conflicts. Could you fix it @{{author}}? 🙏"
      label:
        add:
          - conflict
  #
  # Detect when PR conflict is cleared and remove label
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  #
  # Automatically close PR after 14 days
  - name: close stale pull request
    conditions:
      - base=main
      - -closed
      - updated-at<14 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it's a mistake.
  #
  # Detect when PR is awaiting review and add label
  - name: waiting for review
    conditions:
      - "#commented-reviews-by<2"
      - created-at<1 days ago
      - -draft
    actions:
      label:
        add:
          - waiting for review
  #
  # Detect when PR received review and remove label
  - name: remove waiting for review label if not needed
    conditions:
      - "#commented-reviews-by>=2"
      - -draft
    actions:
      label:
        remove:
          - waiting for review
  #
  # Detect when PR includes a bug fix and add label
  - name: add bug fix label
    conditions:
      - body~=(?m)^- \[[xX]\] Bug fix \(non-breaking change which fixes an issue\)
    actions:
      label:
        add:
          - bug fix
  #
  # Detect when PR includes new feature and add label
  - name: add new feature label
    conditions:
      - body~=(?m)^- \[[xX]\] New feature \(non-breaking change which adds functionality\)
    actions:
      label:
        add:
          - new feature
  #
  # Detect when PR includes documentation updates and add label
  - name: add documentation label
    conditions:
      - body~=(?m)^- \[[xX]\] Documentation update
    actions:
      label:
        add:
          - documentation
  #
  # Detect when PR includes tests update and add label
  - name: add test update label
    conditions:
      - body~=(?m)^- \[[xX]\] Tests update
    actions:
      label:
        add:
          - test update

  #
  # Detect when PR no longer includes bug fix and remove label
  - name: remove bug fix label
    conditions:
      - body~=(?m)^- \[ \] Bug fix \(non-breaking change which fixes an issue\)
    actions:
      label:
        remove:
          - bug fix
  #
  # Detect when PR no longer includes new feature and remove label
  - name: remove new feature label
    conditions:
      - body~=(?m)^- \[ \] New feature \(non-breaking change which adds functionality\)
    actions:
      label:
        remove:
          - new feature
  #
  # Detect when PR no longer includes documentation updates and remove label
  - name: remove documentation label
    conditions:
      - body~=(?m)^- \[ \] Documentation update
    actions:
      label:
        remove:
          - documentation
  #
  # Detect when PR no longer includes tests update and remove label
  - name: remove test update label
    conditions:
      - body~=(?m)^- \[ \] Tests update
    actions:
      label:
        remove:
          - test update
  #
  # Detect when PR is ready and add label
  - name: add ready label
    conditions:
      - body~=(?m)^- \[[xX]\] I have commented my code, particularly in hard-to-understand areas
      - body~=(?m)^- \[[xX]\] I have made corresponding changes to the documentation
      - body~=(?m)^- \[[xX]\] I have added tests that prove my fix is effective or that my feature works
      - body~=(?m)^- \[[xX]\] New and existing unit tests pass locally with my changes
      - body~=(?m)^- \[[xX]\] I run `make pre-commit` to check fmt\/vet\/lint\/test-no-fdo
    actions:
      label:
        add:
          - ready
