---
# SIMPLE RHSM AND INSIGHTS REGISTER
#
# e.g.,
# ansible-playbook -i inventory.ini -vv register_edge_device.yml \
# --extra-vars="regfile=vars_register_edge_device.yml" --user joe_user
#
#   regfile : the file containing rhsm account information

- hosts: all
  gather_facts: no
  become: yes

  vars_files:
    - "{{ regfile }}"

  tasks:
  - name: rhsm register
    shell: "subscription-manager register --username {{ rhsm_username }} --password {{ rhsm_password }} --auto-attach --force"
    tags:
    - rhsm_register
    - register

  - name: insights register
    shell: "insights-client --register"
    tags:
    - insights_register
    - register

  - name: rhc connect
    shell: "rhc connect -u {{ rhc_username }} -p {{ rhc_password }}"
    tags:
      - rhc_connect
      - register

  - name: configure rhc worker-playbook for non-production
    lineinfile:
      path: "/etc/rhc/workers/rhc-worker-playbook.toml"
      regexp: '^verify_playbook = true'
      line: 'verify_playbook = false'

  - name: rhcd service enable and start
    service:
      name: rhcd
      state: started
      enabled: true
    tags:
      - rhc_service
