# Bonfire deployment configuration

# Defines where to fetch the file that defines application configs
appsFile:
  host: gitlab
  repo: insights-platform/cicd-common
  path: bonfire_configs/ephemeral_apps.yaml

# (optional) define any apps locally. An app defined here with <name> will override config for app
# <name> in above fetched config.
apps:
- name: edge
  components:
    - name: edge-api
      host: local
      repo: /home/brosa/Development/edge-api
      path: deploy/clowdapp.yaml
      ref: main

