// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clients/repositories/client.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	url "net/url"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	repositories "github.com/redhatinsights/edge-api/pkg/clients/repositories"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// GetBaseURL mocks base method.
func (m *MockClientInterface) GetBaseURL() (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseURL")
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseURL indicates an expected call of GetBaseURL.
func (mr *MockClientInterfaceMockRecorder) GetBaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseURL", reflect.TypeOf((*MockClientInterface)(nil).GetBaseURL))
}

// ListRepositories mocks base method.
func (m *MockClientInterface) ListRepositories(requestParams repositories.ListRepositoriesParams, filters repositories.ListRepositoriesFilters) ([]repositories.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositories", requestParams, filters)
	ret0, _ := ret[0].([]repositories.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepositories indicates an expected call of ListRepositories.
func (mr *MockClientInterfaceMockRecorder) ListRepositories(requestParams, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositories", reflect.TypeOf((*MockClientInterface)(nil).ListRepositories), requestParams, filters)
}
