# This playbook is meant to be an all-in-one
- name: Run the ostree update in a single play without external deps
  become: true
  hosts: localhost
  vars:
    update_number: "@@ .UpdateNumber @@"
    repo_url: "@@ .RepoURL @@"
    repo_content_url: "@@ .RepoContentURL @@"
    ostree_remote_name: "@@ .GoTemplateRemoteName @@"
    ostree_changes_refs: "@@ .RemoteOstreeUpdate @@"
    os_tree_ref: "@@ .OSTreeRef @@"
    ostree_gpg_verify: "false"
    ostree_gpg_keypath: "/etc/pki/rpm-gpg/"
    ostree_remote_template: |
      [remote "{{ ostree_remote_name }}"]
      url={{ repo_url }}
      gpg-verify={{ ostree_gpg_verify }}
      gpgkeypath={{ ostree_gpg_keypath }}
      contenturl={{ repo_content_url }}
      tls-client-key-path=/etc/pki/consumer/key.pem
      tls-client-cert-path=/etc/pki/consumer/cert.pem
    insights_signature_exclude: "/vars/insights_signature,/vars/update_number,/vars/ostree_remote_name,/vars/ostree_changes_refs,/vars/os_tree_ref,/vars/repo_url,/vars/repo_content_url"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldUQmpRV1ZqZG5jMU9FUXJhalZ3VGtGUmFUZHBRUzh2WWpKcFNu
      RkRWVFZ0UkVOM1dGcGFhbFZqWm1WT1kyZE9UVGs0Tm1KeldHTUtVM0F3Y1V0TllrOUdNRkY2UWta
      WFRXVlFSRk5YV210ME4zZG9aa0ZIYWxOUWJWbExSMVo1Vm1nM1JXdHZiV2hHTm1WMFFsRkROVGRM
      YlVrMVJVbFlid3BYTld3clQwRlBWM0pUU2tZelpYQXpTbE41V0hWU05XdDZXR2gyWTFCdE1DOWxO
      RFJNU21zM1lXeFJiRWRtVUhsUlpqbGtaMjVzZEU1SWJWbFVjQ3RHQ25GU2RXUXZNblZ2TlRCclRr
      WXhhRWszYTBoNFZESktTVmhsZHpKMmJuaG1hVkU0ZUZNNGNYa3ZhRkU0WWpkMFRVbHJWVWhGT1ha
      clQweFVhRTB5YzFNS05uRkxSbXBSZFhwQldWWmhlaTltVlhCMVVscE9kRTFLYlZkRFZtZENVRGx0
      UkdWYWNGTlBiVUpsYm10NlNVaGhhMUZqVFdVMGR6SnlVM1J3U3pWVVNncGtUR0ZVU0RoRlNWSnlW
      RkZKYVV4UGFVZG5TVWxSVWtsRE9HSkdiSGx4VUZvMFNWTndTa2hvYkhKVE9YZGxTREZ6VkhGSWFH
      OXhhVkphUW1oNlYzRlZDa2t4TmpZd1RteENLelpMUXpWS0wxWnFOVnBqS3pKUFZqY3dPRVpVT0Za
      TmQyWkZjWE5UZG5SSk5FaEtTbkExZUd0WldXOW5OREJ5VmpsNVUyaHFRVTBLWVhKbFkzWkNhRGhx
      VWxSWFRGaFJRV3MxWTJSMU9GSk5SRmRFZDFoVmIzTjJUamxCWlhKV2IwNTNLMDVVZVVSTVYzWTFP
      V3RIVFhCMVpEVkxXRVV2Y3dwRk5qSnJUa3BLVkRaVlRraE9RVEpuTTNoc2VuQm1hRFZGUTBsbU5Y
      Uk1jbGxyTURkbmVUQmhjakpXU2pobk1UVm1UMHhwZW5ObGRtNTBVRkJ0VUZGTkNtNDJSMkZVUWtG
      b1VHMTBkV2d3UTFGRmVtVTFhRXR1ZGtObUsxUmpkVkZSZGxSclRtNUZVbGh2VTAxblJYTlViamR1
      TVRZeGFVeFRMM2d2TDNKNFdta0tWMGd3UVhOa1RUaERWMmxOZWpoelNHcDRUVWhDV1ZwcVExbG9O
      SGRyY1ZoblRFdDZMMU5aWlhOSWFFeENWRGRKZVhWalExTktWVWN3Ymt4VE9IZ3llZ3BOWXpaQlJr
      TjVNMFE1Y3owS1BVZDBNRGNLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - name: apply templated ostree remote config
      ansible.builtin.copy:
        content: "{{ ostree_remote_template }}"
        dest: /etc/ostree/remotes.d/rhel-edge.conf
    - name: run rpmostree update
      when: not ostree_changes_refs|bool
      ansible.builtin.shell: rpm-ostree upgrade --allow-downgrade
      register: rpmostree_upgrade_out
      changed_when: '"No upgrade available" not in rpmostree_upgrade_out.stdout'
      failed_when: 'rpmostree_upgrade_out.rc != 0'
    - name: run rpmostree rebase
      when: ostree_changes_refs|bool
      ansible.builtin.shell: rpm-ostree rebase "{{ os_tree_ref }}"
      register: rpmostree_rebase_out
      changed_when: '"No upgrade available" not in rpmostree_rebase_out.stdout'
      failed_when: 'rpmostree_rebase_out.rc != 0'
    - name: schedule reboot when rpmostree upgraded
      ansible.builtin.shell: systemd-run --on-active=5 /usr/bin/systemctl reboot
      when: ('rpmostree_rebase_out.changed | "Staging deployment...done" in rpmostree_rebase_out.out') or ('rpmostree_upgrade_out.changed | "Staging deployment...done" in rpmostree_upgrade_out.stdout')
