version: '2'
services:
    edge-api-dbmigrate:
      image: localhost/edge-api:localdev
      env_file:
        - env/edge-api.env
      volumes:
        - ~/dev/git/RedHatInsights/edge-api:/opt/app-root/src:Z
      working_dir: /opt/app-root/src
      command:  go run cmd/migrate/main.go
