version: '2'
services:
    edge-api-dbmigrate:
      image: quay.io/cloudservices/edge-api:latest
      env_file:
        - env/edge-api.env
      volumes:
        - ${HOME}/dev/git/RedHatInsights/edge-api:/opt/app-root/src:Z
        - ${HOME}/devgo:/go:Z
      working_dir: /opt/app-root/src
      command: /usr/bin/edge-api-migrate