version: '2'
secrets:
  edgemgmt_config:
    file: $PWD/podman/env/edgemgmt_config.json
services:
    edge-api-dbmigrate:
      image: localhost/edge-api:localdev
      env_file:
        - env/edge-api.env
      volumes:
        - ~/dev/git/RedHatInsights/edge-api:/opt/app-root/src:Z
      working_dir: /opt/app-root/src
      command:  go run cmd/migrate/main.go
      secrets:
        - source: edgemgmt_config
          target: /tmp/edgemgmt_config.json
