# for local dev, not related to running in cloud
version: '2'
secrets:
  edgemgmt_config:
    file: $PWD/podman/env/edgemgmt_config.json
services:
  edge-api-service:
    working_dir: /opt/app-root/src
    container_name: edge-api-service
    image: localhost/edge-api:localdev
    restart: never
    privileged: true
    ports:
      - 3000:3000
    env_file:
      - env/edge-api.env
    volumes:
      - $PWD:/opt/app-root/src:z
      - $HOME/go:/go:z
      - $HOME/repos/:/tmp/repos:z
      - $HOME/devdata/vartmp:/var/tmp:z
    command: ["go", "run", "main.go"]
    secrets:
      - source: edgemgmt_config
        target: /tmp/edgemgmt_config.json
    depends_on:
      - "postgresql"
      - "kafka"
    deploy:
      resources:
        limits:
          memory: 4G
