info:
  license:
    name: MIT
  title: edge-api
  version: 1.0.0
openapi: 3.0.0
paths:
  /images:
    post:
      operationId: createImage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.Image'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Image'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Composes an image on Image Builder
    get:
      operationId: listImages
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/v1.Image'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Lists all images for an account.
  /images/{imageId}:
    get:
      operationId: getImage
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type : integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Image'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Get an image by id.
  /images/{imageId}/status:
    get:
      operationId: getImageStatus
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type : integer
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: string
                    example: BUILDING
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Get image status.
      description: This method goes to image builder if the image is still building and updates the status if needed.
  /images/{imageId}/repo:
    get:
      operationId: getImageRepo
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type : integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Repo'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Get Image OSTree repo.
      description: Returns the information of the OSTree Repository of a particular Image.
  /images:
    post:
      operationId: Create
      parameters:
      - Name: Image name
        Description: Image Description
        Distribution: rhel-84,
        ImageType: rhel-edge-commit,
        Commit: {
          Arch: x86_64,
          Packages: [
            {
              name: vim
            }
          ]
        }
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Image'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Image'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Image'
          description: There was an internal server error.
      summary: Create new image for update.
      description: Returns the information of the Image.
