info:
  license:
    name: MIT
  title: edge-api
  version: 1.0.0
openapi: 3.0.0
paths:
  /images:
    post:
      operationId: createImage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.Image'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Image'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Composes an image on Image Builder
    get:
      operationId: listImages
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/v1.Image'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Lists all images for an account.
  /images/{imageId}/update:
    post:
      operationId: CreateImageUpdate
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type : integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.Image'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Image'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Composes an Update for a image
  /images/{imageId}:
    get:
      operationId: getImage
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type : integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Image'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Get an image by id.
  /images/{imageId}/status:
    get:
      operationId: getImageStatus
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type : integer
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: string
                    example: BUILDING
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Get image status.
      description: This method goes to image builder if the image is still building and updates the status if needed.
  /images/{imageId}/repo:
    get:
      operationId: getImageRepo
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type : integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Repo'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Get Image OSTree repo.
      description: Returns the information of the OSTree Repository of a particular Image.
  /updates:
    post:
      operationId: UpdateDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.AddUpdate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.UpdateTransaction'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: There was an internal server error.
      summary: Executes a device update.
      description: Executes a device update.
  /updates/{updateID}/update-playbook.yml:
    get:
      operationId: GetUpdatePlaybook
      parameters:
        - name: updateID
          in: path
          required: true
          description: An unique ID to identify the update the playbook belongs to
          schema:
            type: integer
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
                example: ansible playbook for an update
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500": 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
  /updates/device/{DeviceUUID}/updates:
    get:
      operationId: GetUpdateAvailableForDevice
      parameters:
        - name: DeviceUUID
          in: path
          required: true
          description: DeviceUUID
          schema:
            type : string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Image'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Return list of available updates for a device.
      description: Return list of available updates for a device.
      
