info:
  license:
    name: MIT
  title: edge-api
  version: 1.0.0
openapi: 3.0.0
paths:
  /images:
    post:
      operationId: createImage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/v1.Image"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.Image"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Composes an image on Image Builder
    get:
      operationId: listImages
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 100
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/v1.Image"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Lists all images for an account.
  /images/{imageId}/update:
    post:
      operationId: CreateImageUpdate
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/v1.Image"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.Image"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Composes an Update for a image
  /images/{imageId}:
    get:
      operationId: getImage
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.Image"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Get an image by id.
  /images/{ostreeCommitHash}/info:
    get:
      operationId: GetImageByOstree
      parameters:
        - name: ostreeCommitHash
          in: path
          required: true
          description: ostreeCommitHash
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.Image"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Get an image by ostree hash.
  /images/{imageId}/status:
    get:
      operationId: getImageStatus
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: string
                    example: BUILDING
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Get image status.
      description: This method goes to image builder if the image is still building and updates the status if needed.
  /images/{imageId}/repo:
    get:
      operationId: getImageRepo
      parameters:
        - name: imageId
          in: path
          required: true
          description: ImageID
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.Repo"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Get Image OSTree repo.
      description: Returns the information of the OSTree Repository of a particular Image.
  /updates:
    post:
      operationId: UpdateDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/v1.AddUpdate"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.UpdateTransaction"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: There was an internal server error.
      summary: Executes a device update.
      description: Executes a device update.
    get:
      operationId: ListUpdates
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/v1.UpdateTransaction"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: There was an internal server error.
      summary: Gets all device updates.
      description: Gets all device updates.
  /updates/{updateID}:
    get:
      operationId: GetUpdate
      parameters:
        - name: updateID
          in: path
          required: true
          description: An unique ID to identify the update
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.UpdateTransaction"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Gets a single requested update.
      description: Gets a single requested update.
  /updates/{updateID}/update-playbook.yml:
    get:
      operationId: GetUpdatePlaybook
      parameters:
        - name: updateID
          in: path
          required: true
          description: An unique ID to identify the update the playbook belongs to
          schema:
            type: integer
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
                example: ansible playbook for an update
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
  /updates/device/{DeviceUUID}:
    get:
      operationId: GetUpdateStatusForDevice
      parameters:
        - name: DeviceUUID
          in: path
          required: true
          description: DeviceUUID
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.DeviceDetails"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
      summary: Return list of available updates for a device.
      description: Return list of available updates for a device.
  /updates/device/{DeviceUUID}/updates:
    get:
      operationId: GetUpdateAvailableForDevice
      parameters:
        - name: DeviceUUID
          in: path
          required: true
          description: DeviceUUID
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Image:
                      $ref: "#/components/schemas/v1.Image"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Return list of available updates for a device.
      description: Return list of available updates for a device.
  /updates/device/{DeviceUUID}/image:
    get:
      operationId: GetImageInfo
      parameters:
        - name: DeviceUUID
          in: path
          required: true
          description: DeviceUUID
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  Image:
                    $ref: "#/components/schemas/v1.Image"

          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Return image running on device.
      description: Return image running on device.
  /devices/{DeviceUUID}:
    get:
      operationId: getDevice
      parameters:
        - name: DeviceUUID
          in: path
          required: true
          description: DeviceUUID
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.DeviceDetails"
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.NotFound"
          description: The device was not found.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Get a device by UUID.
  /image-sets:
    get:
      operationId: ListAllImageSets
      parameters:
        - name: sort_by
          in: query
          description: "Define sort fields: Created_at, Name, Status. To sort DESC use -"
          schema:
            type: string
        - name: filter 
          in: query
          description: "field: status =? or name=?"
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  Count:
                    type: integer
                    example: 100
                  Data:
                    type: array
                    items:
                      $ref: "#/components/schemas/v1.ImageSetDetails"
          description: OK
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.NotFound"
          description: The Image Set was not found.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error. 
      summary: Return the list of image sets.     
  /image-sets/{ImageSetId}:
    get:
      operationId: GetImageSetsByID
      parameters:
        - name: ImageSetId
          in: path
          required: true
          description: ImageSetId
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.ImageSetDetails"
          description: OK
  /checkImageName:
    post:
      operationId: checkImageName
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/v1.Image"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.CheckImageResponse"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.BadRequest"
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v1.InternalServerError"
          description: There was an internal server error.
      summary: Check if image name is in use for current account 
  /thirdpartyrepo:
    post:
      operationId: CreateThirdPartyRepo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.CreateThirdPartyRepo'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.CreateThirdPartyRepo'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Create Third Party Repository for an account.
    get:
      operationId: GetAllThirdPartyRepo
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 100
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/v1.CreateThirdPartyRepo'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.BadRequest'
          description: The request sent couldn't be processed.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.InternalServerError'
          description: There was an internal server error.
      summary: Lists all Third Party Repository for an account.
