---
apiVersion: v1
kind: Pod
metadata:
  name: cypress
spec:
  serviceAccountName: "IQE_SERVICE_ACCOUNT"
  containers:
  - command:
    - "/bin/cat"
    image: quay.io/cloudservices/automation-analytics-cypress-image:latest
    imagePullPolicy: Always
    name: cypress
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    stdin: true
    tty: true
  imagePullSecrets:
  - name: quay-cloudservices-pull
  restartPolicy: Never
